name: okrakale_recipe_app
description: Recipe app to browse recipes and manage ingredients

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.20  # Add url_launcher to your dependencies  
  cupertino_icons: ^1.0.2

dev_dependencies:
  mockito: ^5.0.16
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/recipes/smoothies.json
    - assets/recipes/desserts.json
    - assets/recipes/seafoodrecip.json
    - assets/recipes/international.json
    - assets/recipes/italianrecipe.json
    - assets/recipes/indian.json
    - assets/images/background/kitchen_background.jpg
    - assets/images/recipes/smoothie_icon.png
    - assets/images/icons/add_icon.png
    - assets/images/icons/favorite_icon.png
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "assets/ui/icons/app_icon.png"


